### ISSUE TITLE
.dockstore.yml authorship + WDL meta authorship = 200% workflow authorship

### ISSUE THREAD

**Issue by aofarrel** [dockstore/dockstore#4888]
**Describe the bug**
Dockstore thinks I wrote [assoc-aggregate](https://dockstore.org/workflows/github.com/DataBiosphere/analysis_pipeline_WDL/assocation-aggregate-wdl:update-dockstore.yml?tab=info) twice. 

<img width="941" alt="author" src="https://user-images.githubusercontent.com/27784612/166086526-00abfb5c-2f60-43a9-be0c-c5389d6cc56b.png">

**To Reproduce**
1. Have a .dockstore.yml without authorship information describe a WDL with authorship information via meta{}
2. Observe that data is pulled into the Dockstore entry
3. [Add ORCID information to the .dockstore.yml](https://github.com/DataBiosphere/analysis_pipeline_WDL/commit/d18d3e922b5b838b4181ef22eb80a03ed49ebdd6)
4. Instantly double your workflow authorship

**Expected behavior**
When the name of a workflow author matches the name on a .dockstore.yml for a workflow, pick one or the other to display. This won't cover every situation, such as if I had put my legal name as my ORCID name, but it would cover some situations.

**Additional context**
See also https://github.com/dockstore/dockstore/issues/286 and https://github.com/dockstore/dockstore/issues/4621

[Webservice](https://github.com/dockstore/dockstore/releases/tag/1.12.0) - 1.12.0
[UI](https://github.com/dockstore/dockstore-ui2/releases/tag/2.9) - 2.9
[Compose Setup](https://github.com/dockstore/compose_setup/releases/tag/1.12.0-rc.1) - 1.12.0-rc.1
[Deploy](https://github.com/dockstore/dockstore-deploy/releases/tag/1.12.3) - 1.12.3

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-2164)
┆fixVersions: Dockstore 1.12.x
┆friendlyId: DOCK-2164
┆sprint: 87 Octocat
┆taskType: Story

**Comment by kathy-t** [comment]
This bug occurs with a CWL workflow as well. The expected behaviour when I implemented it is the following:
1. If the .dockstore.yml specifies an author, then only the .dockstore.yml's authors should be taken into consideration.

2. If there's no .dockstore.yml, then the author would be taken from the descriptor.

The code must've missed checking if there are ORCID .dockstore.yml authors when creating descriptor authors. This bug only occurs when there are only ORCID .dockstore.yml authors. If the .dockstore.yml has a non-ORCID author along with the ORCID author, the descriptor author is not shown, as expected.

**Comment by aofarrel** [comment]
> If the .dockstore.yml has a non-ORCID author along with the ORCID author, the descriptor author is not shown, as expected.
Is this still the case when you add an author after the fact? Tried doing that in a recent commit and it still has my name show up twice. https://github.com/DataBiosphere/analysis_pipeline_WDL/commit/eabe7da8af367f7f240f94e43f2098225e869907

**Comment by kathy-t** [comment]
> Is this still the case when you add an author after the fact? Tried doing that in a recent commit and it still has my name show up twice. https://github.com/DataBiosphere/analysis_pipeline_WDL/commit/eabe7da8af367f7f240f94e43f2098225e869907

@aofarrel Apologies for the late reply, I just noticed your comment now. In that case, you're really registering two authors, one ORCID author, and one non-ORCID author. We don't check for duplicate authors between ORCID and non-ORCID authors in the .dockstore.yml. Ideally, you just specify one or the other, not both.

**Comment by aofarrel** [comment]
Pushed a new commit to the affected branch and there is indeed only one author now. My email no longer shows up at all now, which I'm fine with. Thanks!

<img width="996" alt="Screen Shot 2022-08-03 at 12 34 47 PM" src="https://user-images.githubusercontent.com/27784612/182694105-a53c5caa-8de9-4622-8636-abe30f727f45.png">

**Comment by aofarrel** [comment]
Turns out this is still an issue on the ld pruning workflow. https://dockstore.org/workflows/github.com/DataBiosphere/analysis_pipeline_WDL/ld-pruning-wdl:update-dockstore.yml?tab=info
<img width="980" alt="Screen Shot 2022-08-03 at 12 41 02 PM" src="https://user-images.githubusercontent.com/27784612/182695181-6ed85cee-8fe1-41f1-b24d-6c7725995382.png">

**Comment by kathy-t** [comment]
I think for that workflow, the [.dockstore.yml defines two separate authors](https://github.com/DataBiosphere/analysis_pipeline_WDL/blob/c72b0eec95ddf5cf03d128a7dd5abed9e19df956/.dockstore.yml#L16-L19), an ORCID author and a normal author with just the name defined.
```
name: ld-pruning-wdl
    authors:
      - orcid: 0000-0003-4896-1858
      - name: Ash O'Farrell
```

This creates two author entries in the table, one from ORCID and just one with the name you provided. Since both your ORCID author and normal author have the same names, it appears as if you have duplicates. We don't check for duplicates within the .dockstore.yml authors. Ideally, if an ORCID author is specified then a separate author entry for the same author specifying the name isn't necessary.

> Even curiouser, ldprune's WDL meta section does have an email, but it's not showing up under either of my clones.

The email isn't showing up because this author info isn't retrieved from the descriptor. It's from this .dockstore.yml author entry here:
https://github.com/DataBiosphere/analysis_pipeline_WDL/blob/update-dockstore.yml/.dockstore.yml#L19

**Comment by aofarrel** [comment]
I'm a fool. 🤦 You're absolutely right, this is on me, forgot to delete that line. All is well!
